/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApplicationappIdemailOwner struct {
	Name *ApplicationappIdemailOwnerName `json:"name,omitempty"`
	// The owner's email address.
	Email string `json:"email,omitempty"`
	// The owner's ID, unique from other owners in this application. If not provided, a UUID is automatically generated.
	OwnerId string `json:"owner_id,omitempty"`
}
