/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package qualpay

type StatementFeeData struct {
	// For INTERNAL USE ONLY.
	RecIdLinked int64 `json:"rec_id_linked,omitempty"`
	// <strong>Format: </strong>Variable length, up to 16 N<br><strong>Description: </strong>Unique ID assigned to a merchant.
	MerchantId int64 `json:"merchant_id,omitempty"`
	// Billing month of the statement in YYYY-MM-DD.
	BillingMonth string `json:"billing_month,omitempty"`
	// The category defines the type of fees.
	FeeCategory string `json:"fee_category,omitempty"`
	// The count of items applicable to the category.
	Count int64 `json:"count,omitempty"`
	// The dollar amount of items applicable to the category.
	AmtFees float64 `json:"amt_fees,omitempty"`
	// The percentage rate applied to the category item.
	PerItem float64 `json:"per_item,omitempty"`
	// The per item rate applied to the category item.
	Rate        float64 `json:"rate,omitempty"`
	DiscountDue float64 `json:"discount_due"`
	// The description of a category item.
	Description string `json:"description,omitempty"`
	// Any fees paid during the month.
	FeesPaid float64 `json:"fees_paid,omitempty"`
	// The total amount of fees due for the category item.
	FeesTotal float64 `json:"fees_total,omitempty"`
}
