/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CheckoutLink struct {
	// <strong>Format: </strong>Fixed length, 32 AN<br><strong>Description: </strong>A unique identifier that is generated when a checkout record is created. It can be stored as a reference to the checkout and used to pull payment details.
	CheckoutId string `json:"checkout_id,omitempty"`
	// <strong>Format: </strong>Variable length, up to 128 AN<br><strong>Description: </strong>A redirect link that will direct a customer to the payment page. This link is unique for each checkout.
	CheckoutLink string `json:"checkout_link,omitempty"`
	// <strong>Format: </strong>Variable length, up to 20 N<br><strong>Description: </strong>Unique ID assigned to a Merchant
	MerchantId int64 `json:"merchant_id,omitempty"`
	// <strong>Format: </strong>Variable length, up to 25 AN<br><strong>Description: </strong>The purchase identifier (also referred to as the invoice number) generated by the merchant.
	PurchaseId string `json:"purchase_id,omitempty"`
	// <strong>Format: </strong>Variable length, up to 12,2 N<br><strong>Description: </strong>Transaction amount from the request message.
	AmtTran float64 `json:"amt_tran,omitempty"`
	// <strong>Format: </strong>Fixed length, 3 AN<br><strong>Description: </strong>Numeric currency code of the checkout transaction. Refer to <a href=\"/developer/api/reference#country-codes\" target=\"_blank\">Country Codes</a> for a list of currency codes.
	TranCurrency string `json:"tran_currency,omitempty"`
	// <strong>Format: </strong>Variable length AN<br><strong>Description: </strong>This field contains the request creation timestamp. 
	DbTimestamp string `json:"db_timestamp,omitempty"`
	// <strong>Format: </strong>Variable length AN<br><strong>Default: </strong>This field contains the timestamp when the checkout_link will expire.  A link will expire once the complete payment is made or if the current date is past the expiry time.  Once a link expires, redirects to the link will be forwarded to your failure URL if provided or to the Checkout error page if failure URL is not provided. 
	ExpiryTime string `json:"expiry_time,omitempty"`
}
