/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package qualpay

type SalesTax struct {
	// <strong>Format: </strong>Variable length, up to 10 AN<br><strong>Description: </strong>Sales Tax type. Possible values are  <br><strong>RATE<strong> The value field contains the tax rate. The system will automatically calculate the tax amount based on the rate.  <br><strong>AMOUNT<strong> The value field contains the tax amount.
	Type_ string `json:"type,omitempty"`
	// <strong>Format: </strong>Variable length, up to 7,5 N<br><strong>Description: </strong>Sales Tax value.If type is RATE, set this field to the sales tax rate. The system will automatically calculate the  sales tax amount (amt_tax) based on the rate. <br>If type is AMOUNT, set this field to the sales tax amount.
	Value float64 `json:"value,omitempty"`
}
