/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package qualpay

type PricingModel struct {
	// Unique ID assigned to this pricing plan.
	PricingId int64      `json:"pricing_id,omitempty"`
	Plan      *PlanModel `json:"plan,omitempty"`
}
