/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Contact struct {
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>First name of the contact.<br><strong>Conditional Requirement: </strong>Required for billing_contact.
	FirstName string `json:"first_name,omitempty"`
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>Last name of the contact.<br><strong>Conditional Requirement: </strong>Required for billing_contact.
	LastName string `json:"last_name,omitempty"`
	// <strong>Format: </strong>Variable length, up to 64 AN<br><strong>Description: </strong>Contact business name, if applicable.<br><strong>Conditional Requirement: </strong>Required for from_contact.
	FirmName string `json:"firm_name,omitempty"`
	// <strong>Format: </strong>Variable length, up to 128 AN<br><strong>Description: </strong>Contact address line item 1.
	Address1 string `json:"address1,omitempty"`
	// <strong>Format: </strong>Variable length, up to 128 AN<br><strong>Description: </strong>Contact address line item 2.
	Address2 string `json:"address2,omitempty"`
	// <strong>Format: </strong>Variable length, up to 64 AN<br><strong>Description: </strong>Contact city.
	City string `json:"city,omitempty"`
	// <strong>Format: </strong>Variable length, up to 64 AN<br><strong>Description: </strong>Contact state.
	State string `json:"state,omitempty"`
	// <strong>Format: </strong>Variable length, up to 10 AN<br><strong>Description: </strong>Contact zip.
	Zip string `json:"zip,omitempty"`
	// <strong>Format: </strong>Variable length, up to 4 N<br><strong>Description: </strong>Contact zip+4 code if applicable.
	Zip4 string `json:"zip4,omitempty"`
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>Contact's phone number.<br><strong>Conditional Requirement: </strong>Required for from_contact.
	Phone string `json:"phone,omitempty"`
	// <strong>Format: </strong>Variable length, up to 64 AN<br><strong>Description: </strong>Contact's email address.
	EmailAddress string `json:"email_address"`
	// <strong>Format: </strong>Variable length, up to 3 AN<br><strong>Description: </strong>ISO numeric country code for the contact. Refer to <a href=\"/developer/api/reference#country-codes\" target=\"_blank\">Country Codes</a> for a list of country codes.<br>
	CountryCode string `json:"country_code,omitempty"`
	// <strong>Format: </strong>Variable length, up to 128 AN<br><strong>Description: </strong>Country name.
	Country string `json:"country,omitempty"`
}
