/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ArdefResponse struct {
	// <strong>Format: </strong>Fixed length, 32 AN<br><strong>Description: </strong>32-byte unique identifier generated by the payment gateway, returned in all valid responses.
	PgId string `json:"pg_id,omitempty"`
	// <strong>Format: </strong>Fixed length, 3 AN<br><strong>Description: </strong>Response code from the payment gateway. \"000\" indicates success. Refer to <a href=\"/developer/api/reference#payment-gateway-response-codes\" target=\"_blank\">Payment Gateway Response Codes</a> for entire list of Payment Gateway Response Codes.
	Rcode string `json:"rcode,omitempty"`
	// <strong>Format: </strong>Variable length<br><strong>Description: </strong>Response text from the payment gateway.
	Rmsg string `json:"rmsg,omitempty"`
	// <strong>Format: </strong>Fixed length, 1 AN<br><strong>Description: </strong>Funding type for a card type request submitted.<ul><li> C - Credit</li><li> D - Debit</li><li>P - Prepaid</li></ul>
	FundingSource string `json:"funding_source,omitempty"`
	// <strong>Format: </strong>Fixed length, 2 AN<br><strong>Description: </strong>Issuer Country for a card type request submitted.
	IssuerCountry string `json:"issuer_country,omitempty"`
	// <strong>Format: </strong>Fixed length, 1 AN<br><strong>Description: </strong>This field will be set to Y for Level 2 purchasing cards.
	IndCommLevel2 string `json:"ind_comm_level2,omitempty"`
	// <strong>Format: </strong>Fixed length, 1 AN<br><strong>Description: </strong>This field will be set to Y for Level 3 purchasing cards.
	IndCommLevel3 string `json:"ind_comm_level3,omitempty"`
}
