/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package qualpay

type PayeeAccountResponse struct {
	// <strong>Format: </strong>Fixed length, 1 AN<br><strong>Description:</strong> Bank Account Type. Possible values are: <br> <ul> <li>`C` - Personal checking account</li> <li>`S` - Personal savings account</li> <li>`K` - Business checking account</li> <li>`V` - Business savings account</li> </ul>
	TypeId string `json:"type_id,omitempty"`
	// <strong>Format: </strong>Fixed length, 9 N <br> <strong>Description:</strong>Bank transit/routing number.
	TrNumber string `json:"tr_number,omitempty"`
	// <strong>Format: </strong>Variable length, up to 17 N<br><strong>Description: </strong>Owner's account number at the bank.
	DdaNumber string `json:"dda_number,omitempty"`
	// <strong>Format: </strong>Variable length, AN<br><strong>Description: </strong>Account holder name
	AccountholderName string `json:"accountholder_name,omitempty"`
	// <strong>Format: </strong>Variable length<br><strong>Description: </strong>Verified Date. The date the account was last verified successfully.
	VerifiedDate string `json:"verified_date,omitempty"`
}
