/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type StatementSettlementData struct {
	// For INTERNAL USE ONLY.
	RecIdLinked int64 `json:"rec_id_linked,omitempty"`
	// <strong>Format: </strong>Variable length, up to 16 N<br><strong>Description: </strong>Unique ID assigned to a merchant.
	MerchantId int64 `json:"merchant_id,omitempty"`
	// Billing month of the statement in YYYY-MM-DD.
	BillingMonth string `json:"billing_month,omitempty"`
	// The date displayed is when a batch settled. Different to the batch date, the settled date displays when the batch was processed by the card brands in YYYY-MM-DD.
	BatchDate time.Time `json:"batch_date,omitempty"`
	// An 11-digit number generated by the product initiating the transaction. The number is available when the transaction is settled and is a unique number that both the acquirer and the issuer can use to identify a transaction. The reference is used as the deposit reference number.
	ReferenceNumber int64 `json:"reference_number,omitempty"`
	// The total funded count of transactions in a settled batch.
	CntPurch float64 `json:"cnt_purch,omitempty"`
	// The total funded value of each transaction in a settled batch.
	AmtPurch float64 `json:"amt_purch,omitempty"`
	// The total amount of refund or credit transactions in a batch.
	AmtReturn float64 `json:"amt_return,omitempty"`
	// The amount deducted from a settled batch prior to merchant funding. These fees apply to accounts set up for net settlement and are the discount percentage applied to each payment transaction and will vary based on the type of payment and the type of the transaction.
	DiscountPaid float64 `json:"discount_paid,omitempty"`
	// The net amount funded to a deposit account.
	AmtNet float64 `json:"amt_net,omitempty"`
	// For INTERNAL USE ONLY.
	SourceId int64 `json:"source_id,omitempty"`
}
