/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CheckoutOptionFields struct {
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>The option fields label on checkout page.
	Label string `json:"label,omitempty"`
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>The option fields description on checkout page.
	Desc string `json:"desc,omitempty"`
	// <br><strong>Description: </strong>The option fields values entered on checkout page.
	Value []string `json:"value,omitempty"`
}
