/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package qualpay

type ArdefRequest struct {
	// <strong>Format: </strong>Variable length, up to 19 N<br><strong>Description: </strong>Cardholder's card number.
	CardNumber string `json:"card_number"`
	// <strong>Format: </strong>Variable length, up to 12 N<br><strong>Description: </strong>Unique identifier on our system.
	MerchantId int64 `json:"merchant_id"`
}
