/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PgShippingAddress struct {
	// <br><strong>Default: </strong>false<br><strong>Description: </strong>Identifies the primary shipping address where there are multiple shipping addresses.
	Primary bool `json:"primary,omitempty"`
	// <strong>Format: </strong>Variable length<br><strong>Description: </strong>Customer street and number, P.O. box, c/o.
	ShippingAddr1 string `json:"shipping_addr1"`
	// <strong>Format: </strong>Variable length<br><strong>Description: </strong>Customer apartment, suite, unit, building, floor, etc.
	ShippingAddr2 string `json:"shipping_addr2,omitempty"`
	// <strong>Format: </strong>Variable length<br><strong>Description: </strong>Customer shipping city.
	ShippingCity string `json:"shipping_city"`
	// <strong>Format: </strong>Variable length<br><strong>Description: </strong>Customer shipping country.
	ShippingCountry string `json:"shipping_country,omitempty"`
	// <strong>Format: </strong>Fixed length, 3 N<br><strong>Description: </strong>ISO numeric country code for the shipping address. Refer to <a href=\"/developer/api/reference#country-codes\" target=\"_blank\">Country Codes</a> for a list of country codes. If the country code is provided, the shipping_country will be updated to match the country code. 
	ShippingCountryCode string `json:"shipping_country_code,omitempty"`
	// <strong>Format: </strong>Variable length, up to 64 AN<br><strong>Description: </strong>Business name if applicable. 
	ShippingFirmName string `json:"shipping_firm_name,omitempty"`
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>Customer shipping first name.
	ShippingFirstName string `json:"shipping_first_name"`
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>Customer shipping last name.
	ShippingLastName string `json:"shipping_last_name"`
	// <strong>Format: </strong>Variable length<br><strong>Description: </strong>Customer shipping state (abbreviated).
	ShippingState string `json:"shipping_state"`
	// <strong>Format: </strong>Variable length<br><strong>Description: </strong>Customer shipping zip code.
	ShippingZip string `json:"shipping_zip"`
	// <strong>Format: </strong>Fixed length, 4 N<br><strong>Description: </strong>Customer shipping zip+4 code if applicable.
	ShippingZip4 string `json:"shipping_zip4,omitempty"`
}
