/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package qualpay

type WebhookAuthSetting struct {
	// <strong>Format: </strong>Variable length, up to 128 AN<br><strong>Description: </strong>The HTTP Basic authentication user name. Applicable only if auth_type is BASIC.
	UserName string `json:"user_name,omitempty"`
	// <strong>Format: </strong>Variable length, up to 128 AN<br><strong>Description: </strong>The HTTP Basic authentication password. Applicable only if auth_type is BASIC.
	UserPassword string `json:"user_password,omitempty"`
}
