/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package qualpay

type PgApiEmailReceiptRequest struct {
	// <strong>Format: </strong>Variable length, up to 12 N<br><strong>Description: </strong>Unique identifier on our system.
	MerchantId int64 `json:"merchant_id"`
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>Use to indicate which company developed the integration or the name of the payment solution that is connected to us. Suggested usage is softwareABCv1.0 or companyXYZv2.0.
	DeveloperId string `json:"developer_id,omitempty"`
	//  AN<br><strong>Description: </strong>An array of email addresses to which the transaction receipt should be sent to.
	EmailAddress []string `json:"email_address"`
	//  AN<br><strong>Description: </strong>A link to the logo image that will be included in the transaction receipt.
	LogoUrl string `json:"logo_url,omitempty"`
	// <strong>Format: </strong>Variable length, up to 12 N<br><strong>Description: </strong>Identifies the vendor to which this email receipt request applies.
	VendorId int64 `json:"vendor_id,omitempty"`
}
