/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Invoice struct {
	// <strong>Format: </strong>Variable length, up to 10 N<br><strong>Description: </strong>A unique number generated to identify an invoice. Save this id to manage an invoice.
	InvoiceId int64 `json:"invoice_id,omitempty"`
	// <strong>Format: </strong>Variable length, up to 16 N<br><strong>Description: </strong>Unique ID assigned to a merchant.
	MerchantId int64 `json:"merchant_id,omitempty"`
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>The customer id associated with this invoice. 
	CustomerId string `json:"customer_id,omitempty"`
	FromContact *Contact `json:"from_contact,omitempty"`
	BillingContact *Contact `json:"billing_contact,omitempty"`
	// <strong>Format: </strong>Variable length, up to 25 AN<br><strong>Description: </strong>The Invoice Number (also referred to as the purchase identifier) generated by the merchant. 
	InvoiceNumber string `json:"invoice_number,omitempty"`
	// <strong>Format: </strong>Variable length, up to 16 AN<br><strong>Description: </strong>Status of an invoice. Possible values are <br>SAVED - Invoice is in draft state. An invoice in draft state can be updated. <br>OUTSTANDING - Invoice has been mailed to the customer. Once an invoice is sent, only the billing_contact and from_contact can be updated.<br>PAID - Invoice has been paid completely. Once paid, the invoice is locked and cannot be modified. <br>CANCELED - Invoice has been canceled. Once canceled, the invoice is locked and cannot be modified. 
	Status string `json:"status,omitempty"`
	// <strong>Format: </strong>Variable length, up to 10,2 N<br><strong>Description: </strong>The total invoice amount. Typically this will be a sum of the line item total and the tax amount. 
	AmtTran float64 `json:"amt_tran,omitempty"`
	// <strong>Format: </strong>Variable length, up to 10,2 N<br><strong>Description: </strong>Tax amount. This amount is automatically calculated if the tax_rate is provided.
	AmtTax float64 `json:"amt_tax,omitempty"`
	// <strong>Format: </strong>Variable length, up to 10,2 N<br><strong>Description: </strong>Sum of all line item total amounts.
	AmtSubTotal float64 `json:"amt_sub_total,omitempty"`
	// <strong>Format: </strong>Variable length, up to 10,2 N<br><strong>Description: </strong>The amount paid by the customer.
	AmtPaid float64 `json:"amt_paid,omitempty"`
	// <strong>Format: </strong>Variable length, up to 10,2 N<br><strong>Description: </strong>The amount due from the customer. This amount is typically the amt_tran minus amt_paid.
	AmtBalance float64 `json:"amt_balance,omitempty"`
	// <strong>Format: </strong>Variable length, up to 20 AN<br><strong>Description: </strong>The unique payment gateway profile ID to be used when making an invoice payment. 
	ProfileId string `json:"profile_id,omitempty"`
	// <strong>Format: </strong>Fixed length, 3 AN<br><strong>Description: </strong>Numeric Currency Code. Refer to <a href=\"/developer/api/reference#country-codes\" target=\"_blank\">Country Codes</a> for a list of currency codes. 
	TranCurrency string `json:"tran_currency,omitempty"`
	// <strong>Format: </strong>Variable length, up to 750 AN<br><strong>Description: </strong>The invoice footer note. This data will be displayed on the footer of the invoice. 
	FooterNote string `json:"footer_note,omitempty"`
	// <strong>Format: </strong>Variable length, up to 500 AN<br><strong>Description: </strong>The invoice payment terms description.
	PaymentTermsNote string `json:"payment_terms_note,omitempty"`
	CheckoutSettings *CheckoutSettings `json:"checkout_settings,omitempty"`
	// <strong>Format: </strong>Variable length, up to 128 AN<br><strong>Description: </strong>A unique link generated once the invoice is complete and sent out to a customer. Customers can also use this link to view and pay for the invoice. 
	InvoiceLink string `json:"invoice_link,omitempty"`
	SalesTax *SalesTax `json:"sales_tax,omitempty"`
	PaymentTerms *PaymentTerm `json:"payment_terms,omitempty"`
	// <strong>Format: </strong>Fixed length, 10 AN, in YYYY-MM-DD format<br><strong>Description: </strong>The invoice date. 
	DateInvoice string `json:"date_invoice,omitempty"`
	// The invoice line item details. 
	LineItems []LineItem `json:"line_items,omitempty"`
	// <strong>Format: </strong>Fixed length, 10 AN, in YYYY-MM-DD format<br><strong>Description: </strong>The invoice payment date. If multiple payments are made for this invoice, this field will have the latest payment date.
	DatePayment string `json:"date_payment,omitempty"`
	// <strong>Format: </strong>Fixed length, 10 AN, in YYYY-MM-DD format<br><strong>Description: </strong>The invoice due date. This date will be automatically calculated based on the payment_terms.  <br><strong>Default: </strong>Invoice Date
	DateDue string `json:"date_due,omitempty"`
	// <strong>Format: </strong>Fixed length, 10 AN, in YYYY-MM-DD format<br><strong>Description: </strong>The date the invoice was last viewed by the customer. 
	DateLastView string `json:"date_last_view,omitempty"`
	// <strong>Format: </strong>Fixed length, 10 AN, in YYYY-MM-DD format<br><strong>Description: </strong>The date invoice was first sent to the customer. This is the date the invoice status is set to OUTSTANDING. 
	DateSent string `json:"date_sent,omitempty"`
	// <strong>Format: </strong>Fixed length, 10 AN, in YYYY-MM-DD format<br><strong>Description: </strong>The date a reminder or overdue notice will be sent. A reminder notice is sent before the due date, overdue notices are sent after the due date. The reminder and overdue intervals can be configured in the Invoice settings page in Merchant Manager. 
	DateNotice string `json:"date_notice,omitempty"`
	// <strong>Format: </strong>Fixed length  AN, in yyyy-MM-ddTHH:mm:ss.SSS-ZZZZ format<br><strong>Description: </strong>The invoice creation timestamp. 
	DbTimestamp string `json:"db_timestamp,omitempty"`
}
