/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateAccountUpdaterResponse struct {
	// <strong>Format: </strong>Variable length, up to 10 N<br><strong>Description: </strong>A unique id assigned for this account updater request.
	RequestId int64 `json:"request_id,omitempty"`
}
