/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Checkout struct {
	// <strong>Format: </strong>Fixed length, 32 AN<br><strong>Description: </strong>A unique identifier that identifies a checkout.
	CheckoutId string `json:"checkout_id,omitempty"`
	// <strong>Format: </strong>Variable length, up to 128 AN<br><strong>Description: </strong>A redirect link that will direct a customer to the payment page. This link is unique for each checkout.
	CheckoutLink string `json:"checkout_link,omitempty"`
	// <strong>Format: </strong>Variable length AN<br><strong>Description: </strong>The checkout resource creation timestamp. 
	DbTimestamp string `json:"db_timestamp,omitempty"`
	// <strong>Format: </strong>Variable length, up to 16 AN<br><strong>Description: </strong>Unique ID assigned to a merchant.
	MerchantId int64 `json:"merchant_id,omitempty"`
	// <strong>Format: </strong>Variable length AN<br><strong>Description: </strong>The expiration timestamp for the checkout_link. Once expired, the link cannot be used to make a payment.  
	ExpiryTime string `json:"expiry_time,omitempty"`
	// <strong>Format: </strong>Variable length, up to 12,2 AN<br><strong>Description: </strong>The total amount of the transaction including sales tax (if applicable).
	AmtTran float64 `json:"amt_tran"`
	// <strong>Format: </strong>Variable length, up to 12,2 N<br><strong>Description: </strong>Amount pending. Valid only for partial payments. If amount is paid in full, the amt_balance will be 0.
	AmtBalance float64 `json:"amt_balance,omitempty"`
	// <strong>Format: </strong>Fixed length, 3 AN<br><strong>Description: </strong>Numeric currency code of the transaction. Refer to <a href=\"/developer/api/reference#country-codes\" target=\"_blank\">Country Codes</a> for a list of currency codes. If the profile_id field is provided, this field will be overridden by the profile’s tran_currency.
	TranCurrency string `json:"tran_currency,omitempty"`
	// <strong>Format: </strong>Variable length, up to 25 AN<br><strong>Description: </strong>The purchase identifier (also referred to as the invoice number) generated by the merchant.
	PurchaseId string `json:"purchase_id,omitempty"`
	// <strong>Format: </strong>Variable length, up to 20 AN<br><strong>Description: </strong>The unique profile ID that will be used during a payment gateway request. 
	ProfileId string `json:"profile_id,omitempty"`
	// <strong>Format: </strong>Variable length, up to 128 AN<br><strong>Description: </strong>Merchant provided reference value that will be stored with the transaction data and will be included with the transaction data reported in the Merchant Manager. This value will also be attached to any lifecycle transactions (e.g. retrieval requests and chargebacks) that may occur.
	MerchRefNum string `json:"merch_ref_num,omitempty"`
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>The customer's first name. 
	CustomerFirstName string `json:"customer_first_name,omitempty"`
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>The customer's last name.
	CustomerLastName string `json:"customer_last_name,omitempty"`
	// <strong>Format: </strong>Variable length, up to 64 AN<br><strong>Description: </strong>The customer's email address.
	CustomerEmail string `json:"customer_email,omitempty"`
	// <strong>Format: </strong>Variable length, up to 16 AN<br><strong>Description: </strong>The customer's phone number with country code.
	CustomerPhone string `json:"customer_phone,omitempty"`
	// <strong>Format: </strong>Variable length, up to 64 AN<br><strong>Description: </strong>The billing address of the cardholder.
	BillingAddr1 string `json:"billing_addr1,omitempty"`
	// <strong>Format: </strong>Variable length, up to 2 AN<br><strong>Description: </strong>The billing state of the cardholder.
	BillingState string `json:"billing_state,omitempty"`
	// <strong>Format: </strong>Variable length, up to 64 AN<br><strong>Description: </strong>The billing city of the cardholder.
	BillingCity string `json:"billing_city,omitempty"`
	// <strong>Format: </strong>Variable length, up to 10 AN<br><strong>Description: </strong>The billing zip code of the cardholder.
	BillingZip string `json:"billing_zip,omitempty"`
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>The customer id associated with this transaction.
	CustomerId string `json:"customer_id,omitempty"`
	Preferences *CheckoutPreferences `json:"preferences,omitempty"`
	// An array of responses from payment gateway. Each element of the array represents a transaction for this checkout. In addition, if subscribed to a checkout webhook, the transaction object is also posted to the Webhook URL once a checkout payment is made.
	Transactions []GatewayResponse `json:"transactions,omitempty"`
	Subscription *CheckoutSubscription `json:"subscription,omitempty"`
}
