/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApplicationappIdemailOwnerName struct {
	// The user's first name.
	FirstName string `json:"first_name"`
	// The user's last name.
	LastName string `json:"last_name"`
}
