/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package qualpay

type InvoicePayment struct {
	// <strong>Format: </strong>Variable length, up to 10 N<br><strong>Description: </strong>Unique ID assigned to an invoice payment. Save this id for managing invoice payments.
	PaymentId int64 `json:"payment_id,omitempty"`
	// <strong>Format: </strong>Variable length, up to 16 N<br><strong>Description: </strong>Unique ID assigned to a Merchant.
	MerchantId int64 `json:"merchant_id,omitempty"`
	// <strong>Format: </strong>Variable length, up to 16 AN<br><strong>Description: </strong>The mode of payment. <br><ul><li>CARD Invoice checkout payment by customer using a card. A card payment cannot be manually added. </li><li>CASH Cash payment.</li><li>CHECK Check Payment.</li><li>OTHER Other modes of payment.</li></ul>
	Type_ string `json:"type,omitempty"`
	// <strong>Format: </strong>Variable length, up to 10,2 N<br><strong>Description: </strong>Amount paid.
	AmtPaid float64 `json:"amt_paid,omitempty"`
	// <strong>Format: </strong>Variable length AN<br><strong>Description: </strong>A short description of the payment.
	Description string `json:"description,omitempty"`
	// <strong>Format: </strong>Fixed length, 32 AN<br><strong>Description: </strong>the generated Payment Gateway ID for the transaction. Applicable only to CARD type transaction.
	PgId string `json:"pg_id,omitempty"`
	// <strong>Format: </strong>Variable length, up to 10 N<br><strong>Description: </strong>A unique number generated to identify an invoice. Save this id to manage an invoice.
	InvoiceId int64 `json:"invoice_id,omitempty"`
	// <strong>Format: </strong>Fixed length, 10 AN, in YYYY-MM-DD format<br><strong>Description: </strong>Date the payment was made
	DatePayment string `json:"date_payment,omitempty"`
	// <strong>Format: </strong>Variable length, up to 16 AN<br><strong>Description: </strong>Status of an invoice. Possible values are <br><ul><li>SAVED Invoice is in draft state. An invoice in draft state can be updated. </li><li>OUTSTANDING Invoice has been mailed to the customer. Once an invoice is sent, only the billing_contact and from_contact can be updated. </li><li>PAID Invoice has been paid completely. A paid invoice cannot be updated. </li><li>CANCELED Invoice has been canceled. A canceled invoice cannot be updated. </li></ul>
	Status string `json:"status,omitempty"`
	// <strong>Format: </strong>Variable length, up to 3 AN<br><strong>Description: </strong>Numeric Currency Code. Refer to <a href=\"/developer/api/reference#country-codes\" target=\"_blank\">Country Codes</a> for a list of currency codes.
	TranCurrency string `json:"tran_currency,omitempty"`
	// <strong>Format: </strong>Fixed length, 1 AN<br><strong>Description: </strong>Transaction status for CARD payments. The status will be empty for non credit card payments.Possible values are <br><ul><li>A - Transaction is approved</li><li>H - Transaction Held</li><li>C - Transaction is captured</li><li>V - Transaction is voided by Merchant</li><li>v - Transaction is voided by System</li><li>K - Transaction is cancelled</li><li>S - Transaction Settled</li><li>P - Deposit Sent</li><li>N - Transaction Settled, but will be funded directly by issuer</li><li>U - Transaction authorization failed or was declined by issuer</li><li>R - Transaction Rejected</li></ul>
	TranStatus string `json:"tran_status,omitempty"`
}
