/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TransactionData struct {
	// The date the transaction was captured by the merchant.
	TranDate string `json:"tran_date,omitempty"`
	// The bank reference number of the deposit.
	ReferenceNumber string `json:"reference_number,omitempty"`
	// Transaction Status<ul><li>A - Transaction is approved</li><li>H - Transaction Held</li><li>C - Transaction is captured</li><li>V - Transaction is voided by Merchant</li><li>v - Transaction is voided by System</li><li>K - Transaction is cancelled</li><li>D - Transaction is declined by issuer</li><li>F - Transaction failures other than Issuer Declines</li><li>S - Transaction Settled</li><li>P - Deposit Sent</li><li>N - Transaction Settled, and will be funded directly by issuer</li><li>R - Transaction Rejected</li></ul>
	TranStatus string `json:"tran_status,omitempty"`
	// Purchase ID of the transaction
	PurchaseId string `json:"purchase_id,omitempty"`
	// Transaction Amount
	AmtTran float64 `json:"amt_tran,omitempty"`
	// Numeric Currency Code. Refer to <a href=\"/developer/api/reference#country-codes\" target=\"_blank\">Country Codes</a> for a list of currency codes.
	TranCurrency string `json:"tran_currency,omitempty"`
	// The date the batch was settled to us.
	BatchDate string `json:"batch_date,omitempty"`
	// The truncated card number of the dispute.
	CardNumber string `json:"card_number,omitempty"`
}
