/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CheckoutCustomer struct {
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>Customer's first name.
	CustomerFirstName string `json:"customer_first_name,omitempty"`
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>Customer's last name.
	CustomerLastName string `json:"customer_last_name,omitempty"`
	// <strong>Format: </strong>Variable length, up to 64 AN<br><strong>Description: </strong>Customer's email address.
	CustomerEmail string `json:"customer_email,omitempty"`
	// <strong>Format: </strong>Variable length, up to 128 AN<br><strong>Description: </strong>Billing street address. This address will also used for AVS verification if AVS verification is enabled. 
	BillingAddr1 string `json:"billing_addr1,omitempty"`
	// <strong>Format: </strong>Variable length, up to 128 AN<br><strong>Description: </strong>Billing Apt/Suite no.
	BillingAddr2 string `json:"billing_addr2,omitempty"`
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>Billing city.
	BillingCity string `json:"billing_city,omitempty"`
	// <strong>Format: </strong>Variable length, up to 3 AN<br><strong>Description: </strong>Billing state.
	BillingState string `json:"billing_state,omitempty"`
	// <strong>Format: </strong>Variable length, up to 3 AN<br><strong>Description: </strong>Billing Country.
	BillingCountry string `json:"billing_country,omitempty"`
	// <strong>Format: </strong>Variable length, up to 10 AN<br><strong>Description: </strong>Billing zip.This zip code will be used for AVS verification if AVS verification is enabled.
	BillingZip string `json:"billing_zip"`
	// <strong>Format: </strong>Variable length, up to 16 N<br><strong>Description: </strong>The customer's phone number with country code.
	CustomerPhone string `json:"customer_phone"`
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>The customer's firm name.
	CustomerFirmName string `json:"customer_firm_name"`
}
