/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package qualpay

type TransactionRequestData struct {
	// <strong>Format: </strong>Variable length, up to 18 N<br><strong>Description: </strong>Unique ID assigned to this request.
	RecId int64 `json:"rec_id,omitempty"`
	// <strong>Format: </strong>Fixed length, 10 N<br><strong>Description: </strong>An internal number generated to identify a transaction. Requests belonging to the same transaction will have the same qp_id.
	QpId int64 `json:"qp_id,omitempty"`
	// <strong>Format: </strong>Variable length, up to 16 AN<br><strong>Description: </strong>Identifies the merchant to which this transaction belongs.
	MerchantId int64 `json:"merchant_id,omitempty"`
	// <strong>Format: </strong>Variable length,  in YYYY-MM-DD HH:MM:ss format<br><strong>Description: </strong>Transaction time. All times are Pacific time.
	TranTime string `json:"tran_time,omitempty"`
	// <strong>Format: </strong>Fixed length, 10 AN, YYYY-MM-DD format<br><strong>Description: </strong>The date the transaction was captured by the merchant.
	TranDate string `json:"tran_date,omitempty"`
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>The request type of the transaction.
	RequestType string `json:"request_type,omitempty"`
	// <strong>Format: </strong>Fixed length, 1 AN<br><strong>Description: </strong>Transaction status.<ul><li>A - Transaction is approved</li><li>H - Transaction Held</li><li>C - Transaction is captured</li><li>V - Transaction is voided by Merchant</li><li>v - Transaction is voided by System</li><li>K - Transaction is cancelled</li><li>D - Transaction is declined by issuer</li><li>F - Transaction failures other than Issuer Declines</li><li>S - Transaction Settled</li><li>P - Deposit Sent</li><li>N - Transaction Settled, and will be funded directly by issuer</li><li>R - Transaction Rejected</li></ul>
	TranStatus string `json:"tran_status,omitempty"`
	// <br><strong>Description: </strong>Will be set to true if the transaction is disputed.
	DisputeFlag bool `json:"dispute_flag,omitempty"`
	// <strong>Format: </strong>Variable length, up to 12,2 N<br><strong>Description: </strong>Amount refunded if there are any refunds.
	AmtRefunded float64 `json:"amt_refunded,omitempty"`
	// <strong>Format: </strong>Fixed length, 32 AN<br><strong>Description: </strong>The generated payment gateway ID for the transaction.
	PgId string `json:"pg_id,omitempty"`
	// <strong>Format: </strong>Fixed length, 32 AN<br><strong>Description: </strong>If this is a refund request, this field will provided the payment gateway ID of the original transaction.
	PgIdLinked string `json:"pg_id_linked,omitempty"`
	// <strong>Format: </strong>Variable length, up to 12,2 N<br><strong>Description: </strong>Transaction amount.
	AmtTran float64 `json:"amt_tran,omitempty"`
	// <strong>Format: </strong>Fixed length, 3 AN<br><strong>Description: </strong>Numeric currency code of the transaction. Refer to <a href=\"/developer/api/reference#country-codes\" target=\"_blank\">Country Codes</a> for a list of currency codes.
	TranCurrency string `json:"tran_currency,omitempty"`
	// <strong>Format: </strong>Variable length, up to 25 AN<br><strong>Description: </strong>Purchase ID of the transaction.
	PurchaseId string `json:"purchase_id,omitempty"`
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>First name of card holder.
	CardholderFirstName string `json:"cardholder_first_name,omitempty"`
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>Last name of card holder.
	CardholderLastName string `json:"cardholder_last_name,omitempty"`
	// <strong>Format: </strong>Fixed length, 16 AN<br><strong>Description: </strong>Masked card number.
	CardNumber string `json:"card_number,omitempty"`
	// <strong>Format: </strong>Fixed length, 2 AN<br><strong>Description: </strong>Card type of the billing card used for the transaction. Refer to <a href=\"/developer/api/reference#card-types\" target=\"_blank\">Card Types</a> for possible values.
	CardType string `json:"card_type,omitempty"`
	// <strong>Format: </strong>Variable length, up to 6 AN<br><strong>Description: </strong>Authorization code from issuer.
	AuthCode string `json:"auth_code,omitempty"`
	// <strong>Format: </strong>Variable length, up to 11 N<br><strong>Description: </strong>Acquirer reference number is an 11-digit number generated by the product initiating the transaction. It is a unique number that both the acquirer and the issuer can use to identify a transaction. For chargeback adjustments, the acquirer reference number is used as the deposit reference number.
	AcqReferenceNumber string `json:"acq_reference_number,omitempty"`
	// <strong>Format: </strong>Variable length, up to 128 AN<br><strong>Description: </strong>Merchant provided reference number for this transaction.
	MerchRefNum string `json:"merch_ref_num,omitempty"`
	// <strong>Format: </strong>Variable length, up to 8,2 N<br><strong>Description: </strong>Amount of convenience fee. A convenience fee is a fee charged to your customer for the \"convenience\" of being able to pay using an alternative payment channel outside your merchant's customary payment channel.
	AmtConvenienceFee float64 `json:"amt_convenience_fee,omitempty"`
	// <strong>Format: </strong>Variable length, up to 8,2 N<br><strong>Description: </strong>Amount of transaction surcharge fee. A surcharge is a fee added to the cost of a purchase for the \"privilege\" of using a credit card instead of another form of payment,
	AmtTranFee float64 `json:"amt_tran_fee,omitempty"`
	// <strong>Format: </strong>Variable length, up to 25 AN<br><strong>Description: </strong>DBA name used in the transaction.
	DbaName string `json:"dba_name,omitempty"`
	// <strong>Format: </strong>Variable length, up to 10,2 N<br><strong>Description: </strong>The amount funded to the merchant (in funded currency).
	AmtFunded float64 `json:"amt_funded,omitempty"`
	// <strong>Format: </strong>Fixed length, 3 AN<br><strong>Description: </strong>Numeric currency code of the funded amount. Refer to <a href=\"/developer/api/reference#country-codes\" target=\"_blank\">Country Codes</a> for possible values.
	FundedCurrency string `json:"funded_currency,omitempty"`
	// <strong>Format: </strong>Fixed length, 3 AN<br><strong>Description: </strong>Gateway response code. Refer to <a href=\"/developer/api/reference#payment-gateway-response-codes\" target=\"_blank\">Payment Gateway Response Codes</a> for possible values.
	Rcode string `json:"rcode,omitempty"`
	// <strong>Format: </strong>Fixed length, 1 AN<br><strong>Description: </strong>AVS result from card issuer (if avs_zip and optionally avs_address were provided in the request). Refer to <a href=\"/developer/api/reference#avs-result-codes\" target=\"_blank\">Payment Result Codes for AVS</a> for possible values.
	AuthAvsResult string `json:"auth_avs_result,omitempty"`
	// <strong>Format: </strong>Fixed length, 1 AN<br><strong>Description: </strong>CVV2 result from card issuer (if CVV2 data was sent in the request). Refer to <a href=\"/developer/api/reference#cvv2-result-codes\" target=\"_blank\">Payment Result Codes for CVV2</a> for possible values.
	AuthCvv2Result string `json:"auth_cvv2_result,omitempty"`
	// <strong>Format: </strong>Variable length, up to 15 AN<br><strong>Description: </strong>The Authorization transaction identifier is a unique identifier returned by the issuing bank for an electronically authorized transaction.
	AuthTranId string `json:"auth_tran_id,omitempty"`
}
