/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RejectedCards struct {
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>card_id that is not included in the request.
	CardId string `json:"card_id,omitempty"`
	// <strong>Format: </strong>Variable length AN<br><strong>Description: </strong>The reason the card id is not included in the harvest request.
	RejectReason string `json:"reject_reason,omitempty"`
}
