/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CheckoutSettings struct {
	// <br><strong>Description: </strong>If set to true, the customer can edit the transaction amount when making payment on the Invoice checkout page. Set this flag to true if you want to allow the customer to make partial payments. 
	AllowPartialPayments bool `json:"allow_partial_payments,omitempty"`
	// <br><strong>Description: </strong>If set to true and the customer email address is provided, we generate and send a receipt to the customer once a payment is made on the invoice checkout page. 
	EmailReceipt bool `json:"email_receipt,omitempty"`
	// <br><strong>Description: </strong>Applicable only if your merchant account is configured to take ACH payments. If set to true, the checkout page will present ACH as one of the payment modes to the customer. <br><strong>Default: </strong>false
	AllowAchPayment bool `json:"allow_ach_payment,omitempty"`
}
