/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package qualpay

type BillingCard struct {
	// <strong>Format: </strong>Variable length, up to 16 AN<br><strong>Description: </strong>The masked card number.
	CardNumber string `json:"card_number,omitempty"`
	// <strong>Format: </strong>Fixed length, 4 N, MMYY format<br><strong>Description: </strong>Expiration date of card number.
	ExpDate string `json:"exp_date,omitempty"`
	// <strong>Format: </strong>Fixed length, 32 AN<br><strong>Description: </strong>Card ID received from a tokenization request.
	CardId string `json:"card_id,omitempty"`
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>Billing first name.
	BillingFirstName string `json:"billing_first_name,omitempty"`
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>Billing last name.
	BillingLastName string `json:"billing_last_name,omitempty"`
	// <strong>Format: </strong>Variable length, up to 64 AN<br><strong>Description: </strong>Business name on billing card, if applicable.
	BillingFirmName string `json:"billing_firm_name,omitempty"`
	// <strong>Format: </strong>Variable length, up to 128 AN<br><strong>Description: </strong>Array of billing email address.
	BillingEmail []string `json:"billing_email,omitempty"`
	// <strong>Format: </strong>Variable length, up to 128 AN<br><strong>Description: </strong>Billing street address. This address will also be used for AVS verification if AVS verification is enabled.
	BillingAddr1 string `json:"billing_addr1,omitempty"`
	// <strong>Format: </strong>Variable length, up to 128 AN<br><strong>Description: </strong>Billing Address line item 2.
	BillingAddr2 string `json:"billing_addr2,omitempty"`
	// <strong>Format: </strong>Variable length, up to 64 AN<br><strong>Description: </strong>Billing city.
	BillingCity string `json:"billing_city,omitempty"`
	// <strong>Format: </strong>Variable length, up to 3 AN<br><strong>Description: </strong>Billing state.
	BillingState string `json:"billing_state,omitempty"`
	// <strong>Format: </strong>Variable length, up to 10 AN<br><strong>Description: </strong>Billing zip.
	BillingZip string `json:"billing_zip,omitempty"`
	// <strong>Format: </strong>Fixed length, 4 N<br><strong>Description: </strong>Billing zip+4 code if applicable.
	BillingZip4 string `json:"billing_zip4,omitempty"`
	// <strong>Format: </strong>Variable length, up to 128 AN<br><strong>Description: </strong>Billing Country.
	BillingCountry string `json:"billing_country,omitempty"`
	// <strong>Format: </strong>Fixed length, 3 AN<br><strong>Description: </strong>ISO numeric country code for the billing address. Refer to <a href=\"/developer/api/reference#country-codes\" target=\"_blank\">Country Codes</a> for a list of country codes.
	BillingCountryCode string `json:"billing_country_code,omitempty"`
	// <br><strong>Description: </strong>True if this is the default card. The default card will be used in recurring billing payments.<br><strong>Default: </strong>false
	Primary bool `json:"primary,omitempty"`
	// <strong>Format: </strong>Fixed length, 2 AN<br><strong>Description: </strong>Card Type. The card type is derived from the card number. Refer to <a href=\"/developer/api/reference#card-types\" target=\"_blank\">Card Types</a> for a list of card types.
	CardType string `json:"card_type,omitempty"`
	// <strong>Format: </strong>Variable length<br><strong>Description: </strong>Verified Date. The date the card was last verified successfully.
	VerifiedDate string `json:"verified_date,omitempty"`
}
