/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CheckoutRequest struct {
	// <strong>Format: </strong>Variable length, up to 12,2 N<br><strong>Description: </strong>The total amount of the transaction including sales tax (if applicable).
	AmtTran float64 `json:"amt_tran,omitempty"`
	// <strong>Format: </strong>Fixed length, 3 AN<br><strong>Description: </strong>Numeric currency code of the transaction. Refer to <a href=\"/developer/api/reference#country-codes\" target=\"_blank\">Country Codes</a> for a list of currency codes. If the profile_id field is provided, this field will be overridden by the profile’s tran_currency.
	TranCurrency string `json:"tran_currency,omitempty"`
	// <strong>Format: </strong>Variable length, up to 25 AN<br><strong>Description: </strong>The purchase identifier (also referred to as the invoice number) generated by the merchant.
	PurchaseId string `json:"purchase_id,omitempty"`
	// <strong>Format: </strong>Variable length, up to 20 AN<br><strong>Description: </strong>The unique profile ID to be used in payment gateway requests. Specify this field if there are multiple profiles for the same currency or if the request should be processed using specific profile_id. By default, if provided, the profile_id decides the tran_currency field.  When profile_id is used, the tran_currency is not required.
	ProfileId string `json:"profile_id,omitempty"`
	// <strong>Format: </strong>Variable length, up to 128 AN<br><strong>Description: </strong>Merchant provided reference value that will be stored with the transaction and will be included with the transaction data reported in the Merchant Manager. This value will also be attached to any lifecycle transactions (e.g. retrieval requests and chargebacks) that may occur.
	MerchRefNum string `json:"merch_ref_num,omitempty"`
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>The customer first name. If this field value is longer than the maximum allowed length, the name will be truncated to maximum allowed length.
	CustomerFirstName string `json:"customer_first_name,omitempty"`
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>The customer last name. If this field value is longer than the maximum allowed length, the name will be truncated. to maximum allowed length.
	CustomerLastName string `json:"customer_last_name,omitempty"`
	// <strong>Format: </strong>Variable length, up to 64 AN<br><strong>Description: </strong>Customer's business name, if applicable. 
	CustomerFirmName string `json:"customer_firm_name,omitempty"`
	// <strong>Format: </strong>Variable length, up to 64 AN<br><strong>Description: </strong>The email address of the customer.
	CustomerEmail string `json:"customer_email,omitempty"`
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong> A unique id to identify the customer. If this is for a checkout payment request, the checkout transaction will be linked to the customer. If this is a new customer, a new customer record is created. The customer_first_name and customer_last_name fields are required for new customers. This field is applicable only for merchant ids that are configured to use Customer Vault.<br><strong>Conditional Requirement: </strong>This field is required for checkout vault requests.
	CustomerId string `json:"customer_id,omitempty"`
	// <strong>Format: </strong>Fixed length, 32 AN<br><strong>Description: </strong>Card ID from a customer vault record. This field is applicable only for checkout vault requests.<br><strong>Conditional Requirement: </strong>This field is required to update an existing card in customer vault.
	CardId string `json:"card_id,omitempty"`
	// <strong>Format: </strong>Variable length, up to 16 AN<br><strong>Description: </strong>The customer phone number. For non U.S. phone numbers, prefix number with + and country code. For example, for a phone number in UK, send the phone number as +447999999999.
	CustomerPhone string `json:"customer_phone,omitempty"`
	// <strong>Format: </strong>Variable length, up to 64 AN<br><strong>Description: </strong>The billing street address of the cardholder.
	BillingAddr1 string `json:"billing_addr1,omitempty"`
	// <strong>Format: </strong>Variable length, up to 3 AN<br><strong>Description: </strong>The billing state of the cardholder.
	BillingState string `json:"billing_state,omitempty"`
	// <strong>Format: </strong>Variable length, up to 64 AN<br><strong>Description: </strong>The billing city of the cardholder.
	BillingCity string `json:"billing_city,omitempty"`
	// <strong>Format: </strong>Variable length, up to 10 AN<br><strong>Description: </strong>The billing zip code of the cardholder.
	BillingZip string `json:"billing_zip,omitempty"`
	// <strong>Format: </strong>Fixed length, 1 N<br><strong>Default: </strong>7<br><strong>Description: </strong>Indicates type of MOTO transaction: <ul><li>0 = Card Present (not MOTO/e-Commerce)</li><li>1 = One Time MOTO transaction</li><li>2 = Recurring </li><li>3 = Installment </li><li>7 = e-Commerce Channel Encrypted (SSL)</li></ul>
	MotoEcommInd string `json:"moto_ecomm_ind,omitempty"`
	Preferences *CheckoutPreferences `json:"preferences,omitempty"`
	// <strong>Format: </strong>Variable length, up to 10 N<br><strong>Description: </strong>The unique id associated with the checout profile. This id can be retrieved from the Checkout tab in the Settings page. <br><strong>Conditional Requirement: </strong>This field is required if you have multiple active checkout profiles. This field is not required if your account has only one active checkout profile. 
	CheckoutProfileId int64 `json:"checkout_profile_id,omitempty"`
}
