/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package qualpay

type ApiKey struct {
	// The primary security key for the merchant ID requested.
	SecurityKey string `json:"security_key,omitempty"`
}
