/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package qualpay

type CopyInvoiceRequest struct {
	// <strong>Format: </strong>Variable length, up to 25 AN<br><strong>Description: </strong>The invoice number (also referred to as the purchase identifier) generated by the merchant for the cloned invoice. This field is optional, by default if not sent, the cloned invoice will have the same invoice number as the original invoice.
	InvoiceNumber string `json:"invoice_number,omitempty"`
}
