/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package qualpay

import (
	"time"
)

type StatementReserveData struct {
	// For INTERNAL USE ONLY.
	RecIdLinked int64 `json:"rec_id_linked,omitempty"`
	// <strong>Format: </strong>Variable length, up to 16 N<br><strong>Description: </strong>Unique ID assigned to a merchant.
	MerchantId int64 `json:"merchant_id,omitempty"`
	// Identifies the date funds are posted to the depository account for either settled transactions, net of reserve or adjustments for release of reserves. in YYYY-MM-DD.
	BillingMonth string `json:"billing_month,omitempty"`
	// Identifies the date funds are posted to the depository account for either settled transactions, net of reserve or adjustments for release of reserves. in YYYY-MM-DD.
	BatchDate time.Time `json:"batch_date,omitempty"`
	// Is the total dollar amount deducted from settled transactions prior to funding. The amount is calculated by applying an agreed upon percentage to the sales volume in a batch.
	AmtReserve float64 `json:"amt_Reserve,omitempty"`
	// Is the total dollar amount released as an adjustment to the depository account.
	AmtReleasedReserve float64 `json:"amt_released_reserve,omitempty"`
	// Total amount of reserve held as of the ACH Post Date.
	AmtReserveBalance float64 `json:"amt_reserve_balance,omitempty"`
}
