/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package qualpay

type BouncedInvoice struct {
	// <strong>Format: </strong>Variable length, up to 10 N<br><strong>Description: </strong>A unique number generated to identify an invoice. Save this id to manage an invoice.
	InvoiceId int64 `json:"invoice_id,omitempty"`
	// <strong>Format: </strong>Variable length, up to 16 N<br><strong>Description: </strong>Unique ID assigned to a merchant.
	MerchantId int64 `json:"merchant_id,omitempty"`
	// <strong>Format: </strong>Variable length, up to 25 AN<br><strong>Description: </strong>The Invoice Number (also referred to as the purchase identifier) generated by the merchant.
	InvoiceNumber string `json:"invoice_number,omitempty"`
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>The customer id associated with this invoice.
	CustomerId string `json:"customer_id,omitempty"`
	// <strong>Format: </strong>Variable length, up to 16 AN<br><strong>Description: </strong>Status of an invoice. Possible values are <br>SAVED - Invoice is in draft state. An invoice in draft state can be updated. <br>OUTSTANDING - Invoice has been mailed to the customer. Once an invoice is sent, only the billing_contact and from_contact can be updated.<br>PAID - Invoice has been paid completely. Once paid, the invoice is locked and cannot be modified. <br>CANCELED - Invoice has been canceled. Once canceled, the invoice is locked and cannot be modified. <br><strong>Maximum Length: </strong>16
	Status string `json:"status,omitempty"`
	// <strong>Format: </strong>Fixed length, 1 AN<br><strong>Description: </strong>The email client response code. Possible values are <br>O - Email not send. The email address may be invalid.  <br>A - Email not sent. The email address has been disabled. <br>B - Email bounced. <br><strong>Maximum Length: </strong>1
	SendCode string `json:"send_code,omitempty"`
	// <strong>Format: </strong>Variable length AN<br><strong>Description: </strong>The time when the invoice was sent.
	DbTimestamp string `json:"db_timestamp,omitempty"`
	// An array of the invoice recipient's email addresses.
	Recipient []string `json:"recipient,omitempty"`
}
