/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AppIdDataBody struct {
	// An array of data fields to save to the application.
	Data []ApplicationappIddataData `json:"data"`
}
