/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package qualpay

type PgApiBalanceRequest struct {
	// <strong>Format: </strong>Variable length, up to 16 N<br><strong>Description: </strong>Unique identifier on the payments system.
	MerchantId int64 `json:"merchant_id"`
	// <strong>Format: </strong>Variable length, up to 16 N<br><strong>Description: </strong>For Benefit Of (FBO) merchant account identifier on the payments system.
	FboId int64 `json:"fbo_id"`
	// <strong>Format: </strong>Variable length, up to 16 N<br><strong>Description: </strong>[Optional] Identifies the vendor submitting the balance inquiry.
	VendorId int64 `json:"vendor_id,omitempty"`
}
