/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package qualpay

type UpdateDraftRequest struct {
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>The customer_id associated with this invoice. Customer should be a valid customer in the system.
	CustomerId     string   `json:"customer_id"`
	FromContact    *Contact `json:"from_contact,omitempty"`
	BillingContact *Contact `json:"billing_contact,omitempty"`
	// <strong>Format: </strong>Variable length, up to 25 AN<br><strong>Description: </strong>The Invoice Number (also referred to as the purchase identifier) generated by the merchant.
	InvoiceNumber string `json:"invoice_number"`
	// <strong>Format: </strong>Variable length, up to 20 AN<br><strong>Description: </strong>The unique payment gateway profile ID to be used when making an invoice payment. This field is optional, only the tran_currency field can be sent and the system will choose the appropriate profile. If both profile_id and tran_currency is sent, the system will use the profile_id.
	ProfileId string `json:"profile_id,omitempty"`
	// <strong>Format: </strong>Variable length, up to 3 AN<br><strong>Description: </strong>Numeric Currency Code. Refer to <a href=\"/developer/api/reference#country-codes\" target=\"_blank\">Country Codes</a> for a list of currency codes. If both profile_id and tran_currency fields are provided, profile_id is used. tran_currency will be updated to match the profile_id<br><strong>Default: </strong>840
	TranCurrency string `json:"tran_currency,omitempty"`
	// <strong>Format: </strong>Variable length, up to 750 AN<br><strong>Description: </strong>The invoice footer note. This data will be displayed on the footer of the invoice.
	FooterNote string `json:"footer_note,omitempty"`
	// <strong>Format: </strong>Variable length, up to 500 AN<br><strong>Description: </strong>The invoice payment terms description.
	PaymentTermsNote string            `json:"payment_terms_note,omitempty"`
	CheckoutSettings *CheckoutSettings `json:"checkout_settings,omitempty"`
	SalesTax         *SalesTax         `json:"sales_tax,omitempty"`
	PaymentTerms     *PaymentTerm      `json:"payment_terms,omitempty"`
	// <strong>Format: </strong>Fixed length, 10 AN, in YYYY-MM-DD format<br><strong>Description: </strong>The invoice date.
	DateInvoice string `json:"date_invoice,omitempty"`
	// The invoice line item details.
	LineItems []LineItem `json:"line_items,omitempty"`
}
