/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package qualpay

type AddSubscriptionRequest struct {
	// <strong>Format: </strong>Fixed length, 10, YYYY-MM-DD format<br><strong>Description: </strong>Date the subscription will start.
	DateStart string `json:"date_start"`
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>Customer id of the Subscriber. Customer id should be a valid existing customer from customer vault. A customer can also be created on the fly before adding a subscription by using the customer field.<br><strong>Conditional Requirement: </strong>Either customer_id or customer is required.
	CustomerId string `json:"customer_id,omitempty"`
	// <strong>Format: </strong>Fixed length, 32 AN<br><strong>Description: </strong>By default, when a subscription is added to a customer, the recurring charges will be billed to the customer's primary payment method. This can be overridden to charge against any of the customer's payment methods, by sending any card_id belonging to the customer in this field.
	CardId   string              `json:"card_id,omitempty"`
	Customer *AddCustomerRequest `json:"customer,omitempty"`
	// <strong>Format: </strong>Variable length, up to 16 AN<br><strong>Description: </strong>Plan code of the recurring plan. Plan should be active and a valid recurring plan.<br><strong>Conditional Requirement: </strong> Required for on-plan subscriptions
	PlanCode string `json:"plan_code,omitempty"`
	// <strong>Format: </strong>Variable length<br><strong>Description: </strong>A short description of the one off plan. Applicable only to one-off subscriptions.
	PlanDesc string `json:"plan_desc,omitempty"`
	// <strong>Format: </strong>Fixed length 1 N<br><strong>Description: </strong> This field identifies the frequency of billing.  Applicable only to one-off subscriptions. Use one of the following codes for frequency. <ul> <li>0 - Weekly</li> <li>1 - Bi-Weekly</li> <li>3 - Monthly</li> <li>4 - Quarterly</li> <li>5 - Bi-annually</li> <li>6 - Annually</li> <li>7 - Daily</li>   </ul><br><strong>Conditional Requirement: </strong>Required for one-off subscriptions.
	PlanFrequency int32 `json:"plan_frequency,omitempty"`
	// <strong>Format: </strong>Variable length, up to 2 N<br><strong>Description: </strong> Applicable only for monthly or weekly frequency. Number of months in a subscription cycle.
	Interval int32 `json:"interval,omitempty"`
	// <strong>Format: </strong>Variable length, up to 4 N<br><strong>Description: </strong>Number of billing cycles in the recurring subscription, Use -1 if billing cycles are indefinite. Applicable only to one-off subscriptions. <br><strong>Conditional Requirement: </strong>Required for one-off subscriptions.
	PlanDuration int32 `json:"plan_duration,omitempty"`
	// <strong>Format: </strong>Variable length, up to 12,2 N<br><strong>Description: </strong>One-Time Fee amount. This fee will be charged immediately when a subscription is added. Applicable only to one-off subscriptions.
	AmtSetup float64 `json:"amt_setup,omitempty"`
	// <br><strong>Description: </strong> When set to true and if the recurring plan requires a one time fee, the system will not charge the one-time fee amount. By default if a plan has a one-time fee, the customer will be charged the one-time fee when the subscription is created. Set this flag to true if you would like to avoid charging the customer for the plan one-time fee.  <br><strong>Default: </strong>false
	AmtSetupIgnore bool `json:"amt_setup_ignore,omitempty"`
	// <br><strong>Description: </strong> When set to true and if the subscription requires a one time fee, the system will cancel the subscription if the one-time fee cannot be charged successfully. <br><strong>Default: </strong>false
	CancelOnSetupFail bool `json:"cancel_on_setup_fail,omitempty"`
	// <strong>Format: </strong>Variable length, up to 12,2 N<br><strong>Description: </strong>Plan Transaction Amount. Amount that will be billed each cycle period. Applicable only to one-off subscriptions. <br><strong>Conditional Requirement: </strong>Required for one-off subscription.
	AmtTran float64 `json:"amt_tran,omitempty"`
	// <strong>Format: </strong>Fixed length, 20 N<br><strong>Description: </strong>Payment Gateway Profile id that will be used when billing transactions. tran_currency will be used if profile_id is not provided. If both tran_currency and profile_id are not provided, default USD profile is used. Applicable only to one-off subscriptions.
	ProfileId string `json:"profile_id,omitempty"`
	// <strong>Format: </strong>Fixed length, 3 AN<br><strong>Description: </strong>Numeric Currency Code. If profile_id is provided, the currency is determined from profile. Refer to <a href=\"/developer/api/reference#country-codes\" target=\"_blank\">Country Codes</a> for a list of currency codes. Applicable only to one-off subscriptions.<br><strong>Default: </strong>840
	TranCurrency string `json:"tran_currency,omitempty"`
	// <br><strong>Description: </strong> When set to true, the system will try to use an existing customer_id if one is available. If there is an existing customer with the same customer_first_name and customer_last_name and primary card_number or card_id, then the subscription is added to the matching customer.  If a customer is not found, a new customer is generated. The generated customer_id will be returned in the response. <br><strong>Default: </strong>false<br><strong>Conditional Requirement: </strong>If set to true, the field, customer, is required.
	UseExistingCustomer bool `json:"use_existing_customer,omitempty"`
	// <strong>Format: </strong>Variable length, up to 3,2 N<br><strong>Description: </strong>Percentage of transaction that will be added as a surcharge. A surcharge is a fee added to the cost of a purchase for the \"privilege\" of using a credit card instead of another form of payment. Surcharge can be used only if merchant is enabled to use surcharge and if the selected payment supports surcharge.
	PctFee float64 `json:"pct_fee,omitempty"`
	// <strong>Format: </strong>Variable length, up to 25 AN<br><strong>Description: </strong>Purchase Identifier (also referred to as the invoice number generated by the merchant) included in the recurring transactions. If not provided, the system generates a purchase identifier based on customer data. Applicable only to one-off subscriptions.
	PurchaseId string `json:"purchase_id,omitempty"`
	// <strong>Format: </strong>Variable length, up to 16 AN<br><strong>Description: </strong>Identifies the merchant to whom this request applies. Optional field, applicable only if the request is sent on behalf of another merchant.<br><strong>Conditional Requirement: </strong>Required if this request is on behalf of another merchant.
	MerchantId int64 `json:"merchant_id,omitempty"`
}
