/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AusRequestId struct {
	// Account Updater Server Request Id
	RequestId string `json:"request_id,omitempty"`
}
