/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RecurringPlan struct {
	// <strong>Format: </strong>Variable length, up to 16 AN<br><strong>Description: </strong>Unique ID assigned to a merchant.
	MerchantId int64 `json:"merchant_id,omitempty"`
	// <strong>Format: </strong>Variable length, up to 10 N<br><strong>Description: </strong>Unique ID generated for a Plan.
	PlanId int64 `json:"plan_id,omitempty"`
	// <strong>Format: </strong>Variable length, up to 16 AN<br><strong>Description: </strong>A unique alphanumeric code provided by the merchant to identify the plan.
	PlanCode string `json:"plan_code,omitempty"`
	// <strong>Format: </strong>Variable length, up to 64 AN<br><strong>Description: </strong>A unique name assigned to the plan. 
	PlanName string `json:"plan_name,omitempty"`
	// <strong>Format: </strong>Variable length AN<br><strong>Description: </strong>A short description of the plan.
	PlanDesc string `json:"plan_desc,omitempty"`
	// <strong>Format: </strong>Fixed length 1 N<br><strong>Description: </strong> The billing frequency. Possible values are: <ul>      <li>0 - Weekly</li>      <li>1 - Bi-weekly</li>      <li>3 - Monthly</li>      <li>4 - Quarterly</li>      <li>5 - Bi-annually</li>      <li>6 - Annually</li>      <li>7 - Daily</li>   </ul>
	PlanFrequency int32 `json:"plan_frequency,omitempty"`
	// <strong>Format: </strong>Variable length, up to 2 N<br><strong>Description: </strong>Number of months or weeks in a subscription cycle. For example if plan_frequency is 3 (Monthly) and interval is 2, a customer using this plan will be billed every 2 months till the subscription is complete or cancelled. Applicable only for monthly or weekly plan_frequency. <br><strong>Default: </strong>1
	Interval int32 `json:"interval,omitempty"`
	// <strong>Format: </strong>Variable length, up to 4 N<br><strong>Description: </strong> Number of billing cycles in the recurring transaction, -1 indicates bill until cancelled. For example if plan_frequency is 3 (Monthly) and plan_duration is 6, the customer will be billed every month for 6 months.
	PlanDuration int32 `json:"plan_duration,omitempty"`
	// <strong>Format: </strong>Fixed length 1 AN<br><strong>Description: </strong>Status of the plan. <ul><li>E - Active</li><li>A - Archived</li><li>D - Deleted</li></ul>
	Status string `json:"status,omitempty"`
	// <strong>Format: </strong>Variable length, up to 2 N<br><strong>Description: </strong>Number of billing cycles in a trial period.
	TrialDuration int32 `json:"trial_duration,omitempty"`
	// <strong>Format: </strong>Variable length, up to 12,2 N<br><strong>Description: </strong>Amount to be billed during the trial period.
	AmtTrial float64 `json:"amt_trial,omitempty"`
	// <strong>Format: </strong>Variable length, up to 12,2 N<br><strong>Description: </strong>One-time fee amount.
	AmtSetup float64 `json:"amt_setup,omitempty"`
	// <strong>Format: </strong>Variable length, up to 12,2 N<br><strong>Description: </strong>Plan transaction amount. Amount that will be billed each cycle. 
	AmtTran float64 `json:"amt_tran,omitempty"`
	// <strong>Format: </strong>Fixed length, 3 AN<br><strong>Description: </strong>Numeric Currency Code. Refer to <a href=\"/developer/api/reference#country-codes\" target=\"_blank\">Country Codes</a> for a list of currency codes.<br><strong>Default: </strong>840
	TranCurrency string `json:"tran_currency,omitempty"`
	// <strong>Format: </strong>Fixed length, 20 N<br><strong>Description: </strong>Payment gateway profile id that will be used for subscriptions that use this plan. 
	ProfileId string `json:"profile_id,omitempty"`
	// <br><strong>Description: </strong>If set to true, the customer will be billed on a specific start date.<br><strong>Default: </strong>false
	BillSpecificDay bool `json:"bill_specific_day,omitempty"`
	// <strong>Format: </strong>Fixed length, 1 N<br><strong>Description: </strong>This field represents the day of the week on which the system will be billed for weekly or biweekly plans.<ul><li>1 - Sunday</li><li>2 - Monday</li><li>3 - Tuesday</li><li>4 - Wednesday</li><li>5 - Thursday</li><li>6 - Friday</li><li>7 - Saturday</li></ul><br><strong>Conditional Requirement: </strong>Applicable only when billing is on specific day, i.e., bill_specific_day flag is set to true.
	DayOfWeek int32 `json:"day_of_week,omitempty"`
	// <strong>Format: </strong>Variable length, up to 2 N<br><strong>Description: </strong>Day of the month on which the system will be billed for month or year based plans. Use 1-31 to represent the day of month when the customerwill be billed or 32 if billing should be on the last day of month. <br><strong>Conditional Requirement: </strong>Applicable only when billing is on specific day, i.e., bill_specific_day flag is set to true.
	DayOfMonth int32 `json:"day_of_month,omitempty"`
	// <strong>Format: </strong>Variable length, up to 2 N<br><strong>Description: </strong>Month on which the system will be billed for month or year based plans. Possible values are:<ul><li>1 - January</li><li>2 - February</li><li>3 - March</li><li>4 - April</li><li>5 - May</li><li>6 - June</li><li>7 - July</li><li>8 - August</li><li>9 - September</li><li>10 - October</li><li>11 - November</li><li>12 - December</li></ul><br><strong>Conditional Requirement: </strong>Applicable only when billing is on specific day , i.e., bill_specific_day flag is set to true.
	Month int32 `json:"month,omitempty"`
	// <br><strong>Description: </strong>Set this flag to true if the first payment should be prorated. <br><strong>Conditional Requirement: </strong>Applicable only when billing is on specific day , i.e., bill_specific_day flag is set to true.
	ProrateFirstPmt bool `json:"prorate_first_pmt,omitempty"`
	// <strong>Format: </strong>Variable length, up to 12,2 N<br><strong>Description: </strong>Fixed prorate amount for first payment. If set to zero or undefined, the system will calculate the prorate amount based on the number of days remaining in the first cycle. <br><strong>Conditional Requirement: </strong>This field is applicable only if prorate_first_pmt is set to true. 
	AmtProrate float64 `json:"amt_prorate,omitempty"`
	// <strong>Format: </strong>Variable length AN<br><strong>Description: </strong>Date/time the plan was created.
	DbTimestamp string `json:"db_timestamp,omitempty"`
	// <strong>Format: </strong>Variable length AN<br><strong>Description: </strong>Date/time the plan was last modified.
	ModTimestamp string `json:"mod_timestamp,omitempty"`
}
