/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ApplicationModel struct {
	// Unique ID assigned to this application.
	AppId int64 `json:"app_id,omitempty"`
	// Unique ID assigned to a merchant.
	MerchantId int64 `json:"merchant_id,omitempty"`
	// The current status of the application.
	AppStatus string `json:"app_status,omitempty"`
	// The 'doing business as' name, as it is currently on the merchant application.
	DbaName string `json:"dba_name,omitempty"`
	// The timestamp the application was created.
	DbTimestamp time.Time `json:"db_timestamp,omitempty"`
	// The timestamp the application was submitted as complete.
	SubmitTimestamp time.Time `json:"submit_timestamp,omitempty"`
	// The timestamp the application's credit decision was made.
	CreditTimestamp time.Time `json:"credit_timestamp,omitempty"`
}
