/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package qualpay

type Transaction struct {
	// <strong>Format: </strong>Variable length, up to 16 AN<br><strong>Description: </strong>Identifies the merchant to which this transaction belongs.
	MerchantId int64 `json:"merchant_id,omitempty"`
	// <strong>Format: </strong>Variable length,  in YYYY-MM-DD HH:MM:ss format<br><strong>Description: </strong>Transaction time. All times are Pacific time.
	TranTime string `json:"tran_time,omitempty"`
	// <strong>Format: </strong>Fixed length, 10 AN, YYYY-MM-DD format<br><strong>Description: </strong>The date the transaction was captured by the merchant.
	TranDate string `json:"tran_date,omitempty"`
	// <strong>Format: </strong>Fixed length, 1 AN<br><strong>Description: </strong>Transaction status.<ul><li>A - Transaction is approved</li><li>H - Transaction Held</li><li>C - Transaction is captured</li><li>V - Transaction is voided by Merchant</li><li>v - Transaction is voided by System</li><li>K - Transaction is cancelled</li><li>D - Transaction is declined by issuer</li><li>F - Transaction failures other than Issuer Declines</li><li>S - Transaction Settled</li><li>P - Deposit Sent</li><li>N - Transaction Settled, and will be funded directly by issuer</li><li>R - Transaction Rejected</li></ul>
	TranStatus string `json:"tran_status,omitempty"`
	// <strong>Format: </strong>Variable length, up to 6 AN<br><strong>Description: </strong>Authorization code from issuer.
	AuthCode string `json:"auth_code,omitempty"`
	// <strong>Format: </strong>Fixed length, 3 AN<br><strong>Description: </strong>Gateway response code. Refer to <a href=\"/developer/api/reference#payment-gateway-response-codes\" target=\"_blank\">Payment Gateway Response Codes</a> for possible values.
	Rcode string `json:"rcode,omitempty"`
	// <strong>Format: </strong>Fixed length, 16 AN<br><strong>Description: </strong>Masked card number.
	CardNumber string `json:"card_number,omitempty"`
	// <strong>Format: </strong>Fixed length, 2 AN<br><strong>Description: </strong>Card type of the billing card used for the transaction. Refer to <a href=\"/developer/api/reference#card-types\" target=\"_blank\">Card Types</a> for possible values.
	CardType string `json:"card_type,omitempty"`
	// <strong>Format: </strong>Variable length, up to 25 AN<br><strong>Description: </strong>Purchase ID of the transaction.
	PurchaseId string `json:"purchase_id,omitempty"`
	// <strong>Format: </strong>Fixed length, 32 AN<br><strong>Description: </strong>The generated payment gateway ID for the transaction.
	PgId string `json:"pg_id,omitempty"`
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>First name of card holder.
	CardholderFirstName string `json:"cardholder_first_name,omitempty"`
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>Last name of card holder.
	CardholderLastName string `json:"cardholder_last_name,omitempty"`
	// <strong>Format: </strong>Variable length, up to 12,2 N<br><strong>Description: </strong>Transaction amount.
	AmtTran float64 `json:"amt_tran,omitempty"`
	// <strong>Format: </strong>Fixed length, 3 AN<br><strong>Description: </strong>Numeric currency code of the transaction. Refer to <a href=\"/developer/api/reference#country-codes\" target=\"_blank\">Country Codes</a> for a list of currency codes.
	TranCurrency string `json:"tran_currency,omitempty"`
	// <br><strong>Description: </strong>Will be set to true if the transaction is disputed.
	DisputeFlag bool `json:"dispute_flag,omitempty"`
	// <strong>Format: </strong>Variable length, up to 12,2 N<br><strong>Description: </strong>Amount refunded if there are any refunds.
	AmtRefunded float64 `json:"amt_refunded,omitempty"`
	// <strong>Format: </strong>Variable length, up to 3 N<br><strong>Description: </strong>Settlement batch number.
	BatchNumber int64 `json:"batch_number,omitempty"`
	// <strong>Format: </strong>Variable length, up to 25 AN<br><strong>Description: </strong>DBA name used in the transaction.
	DbaName string `json:"dba_name,omitempty"`
	// <strong>Format: </strong>Variable length, up to 32 AN<br><strong>Description: </strong>Customer vault ID.
	CustomerId string `json:"customer_id,omitempty"`
	// <strong>Format: </strong>Variable length, up to 10 N<br><strong>Description: </strong>Subscription identifier.
	SubscriptionId string `json:"subscription_id,omitempty"`
	// <strong>Format: </strong>Variable length, up to 128 AN<br><strong>Description: </strong>Merchant provided reference number for this transaction.
	MerchRefNum string `json:"merch_ref_num,omitempty"`
	// <strong>Format: </strong>Variable length, up to 10 N<br><strong>Description: </strong>Unique ID assigned to this batch.
	BatchId int64 `json:"batch_id,omitempty"`
	// <strong>Format: </strong>Fixed length, 10, YYYY-MM-DD format<br><strong>Description: </strong>The date the batch was closed.
	BatchDate string `json:"batch_date,omitempty"`
	// <strong>Format: </strong>Fixed length, 10, YYYY-MM-DD format<br><strong>Description: </strong>The date we settled the transaction with the issuer.
	SettleDate string `json:"settle_date,omitempty"`
	// <strong>Format: </strong>Variable length, up to 10,2 N<br><strong>Description: </strong>The amount funded to the merchant (in funded currency).
	AmtFunded float64 `json:"amt_funded,omitempty"`
	// <strong>Format: </strong>Fixed length, 3 AN<br><strong>Description: </strong>Numeric currency code of the funded amount. Refer to <a href=\"/developer/api/reference#country-codes\" target=\"_blank\">Country Codes</a> for possible values.
	FundedCurrency string `json:"funded_currency,omitempty"`
	// <strong>Format: </strong>Variable length, up to 4 AN<br><strong>Description: </strong>Reject reason code provided by the issuer. Applicable only if transaction is rejected (tran_status = 'R')
	RejectReason string `json:"reject_reason,omitempty"`
	// <strong>Format: </strong>Variable length, up to 128 AN<br><strong>Description: </strong>A short description of the reject code. Applicable only if transaction is rejected (tran_status = 'R')
	RejectReasonDesc string `json:"reject_reason_desc,omitempty"`
}
