/*
 * APIs
 *
 * This document describes the Platform and PG API.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"os"
)

type RecIdRespondBody struct {
	// The file to upload.
	File **os.File `json:"file"`
	// Dispute response
	DisputeResponse string `json:"disputeResponse"`
}
